name: Build and test

on:
  push:
    branches:
      - dev

jobs:
  echo:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Echo a message
        run: echo "Pushed to dev!"