name: Build and test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  buildTest:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Install MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Install NuGet
        uses: nuget/setup-nuget@v2

      - name: Restore dependencies
        run: nuget restore Software\E_Libra\E_Libra.sln

      - name: Build solution
        run: msbuild.exe Software\E_Libra\E_Libra.sln /p:platform="Any CPU" /p:configuration="Release"

      - name: List build artifacts
        run: dir Software\E_Libra\UnitTesting\bin\Release\net4.8

      - name: Run unit tests
        run: dotnet test Software\E_Libra\UnitTesting\UnitTesting.csproj --no-build --verbosity normal
