name: Build and unit test F16

on:
  push:
    branches:
      - 46-nova-funkcionalnost-f16
  pull_request:
    branches:
      - 46-nova-funkcionalnost-f16
  workflow_dispatch:

jobs:
  buildTest:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Install MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Install NuGet
        uses: nuget/setup-nuget@v2

      - name: Restore dependencies
        run: nuget restore Software\E_Libra\E_Libra.sln

      - name: Build solution
        run: msbuild.exe Software\E_Libra\E_Libra.sln /p:platform="Any CPU" /p:configuration="Debug"

      - name: Build Unit Test project
        run: dotnet build Software\E_Libra\UnitTesting\UnitTesting.csproj --configuration Debug

      - name: Run unit tests
        run: dotnet test Software\E_Libra\UnitTesting\UnitTesting.csproj --no-build --verbosity normal