name: Build and test

on:
	push:
		branches:
			- dev
		pull_request:
			branches:
				- dev
		workflow_dispatch:

jobs:
	buildTest:
	
		runs-on: windows-latest
		steps:
			- name: Checkout
				uses: actions/checkout@v4.1.6
				
			- name: Install MSBuild
				uses: microsoft/setup-msbuild@v2
				
			- name: Install NuGet
				uses: NuGet/setup-nuget@2.0.0
			
			- name: Restore dependencies
				run: nuget restore
			
			- name: Build solution
				run: msbuild.exe Software\E_Libra\E_Libra.sln /p:platform="Any CPU" /p: configuration="Release"